### ISSUE TITLE
Plugin can't be activated in Godot

### ISSUE THREAD

**Issue by Twyker** [wmigor/godot-mono-custom-resource-register#1]
Problem:
When trying to activate the plugin in Godot's project settings, it encounters an error:
```Unable to load addon script from path: 'res://addons/CustomResourceRegister/Plugin.cs' There seems to be an error in the code, please check the syntax.```
Version:
Godot 3.2.3 stable

VSCode sees no error in the code though.

**Comment by Jamesthe1** [comment]
Can confirm, Godot v3.3. [This issue](https://github.com/godotengine/godot/issues/39921) seems to be the culprit, still open. Appears to only happen for plugins built with C#.

**Comment by wmigor** [comment]
Install:
- clone this repository and move folder addons/CustomResourceRegister in {your project}/addons/
- add this folder to project in IDE
- build solution
- enable addon in settings

**Comment by Jamesthe1** [comment]
The plugin's files are *not* added to the build list automatically and therefore this is not a working solution. They would only be added if the files were created manually via the editor, or by hand in the C# project file (.csproj) at project root.
